-- public schema

-- !Ups

CREATE TABLE public.messages (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ) PRIMARY KEY,
    content text NOT NULL
);

CREATE TABLE public.users (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ) PRIMARY KEY,
    username text NOT NULL,
    password text NOT NULL
);

-- Username: test, Password: test
INSERT INTO public.users (username, password) VALUES ('test', '$2a$10$tdBXWNyNDnp0HbnjWtK3g./HquMyK8WUH9sWr937J9AAwW1kIrs3G');

-- !Downs
DROP TABLE users;
DROP TABLE messages;